// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuraEx.Authoring.Infrastructure;

#nullable disable

namespace QuraEx.Authoring.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603072311_InitAuthoring")]
    partial class InitAuthoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuraEx.Authoring.Domain.Entities.AcceptanceCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserStoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_story_id");

                    b.HasKey("Id")
                        .HasName("pk_acceptance_criteria");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_acceptance_criteria_parent_id");

                    b.HasIndex("UserStoryId")
                        .HasDatabaseName("ix_acceptance_criteria_user_story_id");

                    b.ToTable("acceptance_criteria", (string)null);
                });

            modelBuilder.Entity("QuraEx.Authoring.Domain.Entities.BusinessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserStoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_story_id");

                    b.HasKey("Id")
                        .HasName("pk_business_rule");

                    b.HasIndex("UserStoryId")
                        .HasDatabaseName("ix_business_rule_user_story_id");

                    b.ToTable("business_rule", (string)null);
                });

            modelBuilder.Entity("QuraEx.Authoring.Domain.Entities.UserStory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AsA")
                        .HasColumnType("text")
                        .HasColumnName("as_a");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_ref");

                    b.Property<string>("IWantTo")
                        .HasColumnType("text")
                        .HasColumnName("i_want_to");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SoThat")
                        .HasColumnType("text")
                        .HasColumnName("so_that");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_user_story");

                    b.ToTable("user_story", (string)null);

                    b.HasAnnotation("Npgsql:UseXminAsConcurrencyToken", true);
                });

            modelBuilder.Entity("QuraEx.Authoring.Infrastructure.MembershipSnapshot", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_membership_snapshot");

                    b.ToTable("membership_snapshot", (string)null);
                });

            modelBuilder.Entity("QuraEx.BuildingBlocks.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Seq"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_authoring_outbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_authoring_outbox_message_processed_at");

                    b.ToTable("authoring_outbox_message", (string)null);
                });

            modelBuilder.Entity("QuraEx.BuildingBlocks.Persistence.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId")
                        .HasName("pk_authoring_processed_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_authoring_processed_message_processed_at");

                    b.ToTable("authoring_processed_message", (string)null);
                });

            modelBuilder.Entity("QuraEx.Authoring.Domain.Entities.AcceptanceCriteria", b =>
                {
                    b.HasOne("QuraEx.Authoring.Domain.Entities.AcceptanceCriteria", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_acceptance_criteria_acceptance_criteria_parent_id");

                    b.HasOne("QuraEx.Authoring.Domain.Entities.UserStory", null)
                        .WithMany("AcceptanceCriteria")
                        .HasForeignKey("UserStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acceptance_criteria_user_stories_user_story_id");
                });

            modelBuilder.Entity("QuraEx.Authoring.Domain.Entities.BusinessRule", b =>
                {
                    b.HasOne("QuraEx.Authoring.Domain.Entities.UserStory", null)
                        .WithMany("BusinessRules")
                        .HasForeignKey("UserStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_rule_user_stories_user_story_id");
                });

            modelBuilder.Entity("QuraEx.Authoring.Domain.Entities.UserStory", b =>
                {
                    b.Navigation("AcceptanceCriteria");

                    b.Navigation("BusinessRules");
                });
#pragma warning restore 612, 618
        }
    }
}
